name: QBrix-QLabs-Publish
on:
  push:
    branches: ["main"]

  workflow_dispatch:
env:
  CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
  CUMULUSCI_SERVICE_github: ${{ secrets.QBRIX_CUMULUSCI_SERVICE_github }}
  SFDX_CLIENT_ID: ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}
  SFDX_HUB_KEY: ${{ secrets.QBRIX_DEVHUB_PRIVATE_KEY }}
  DEVHUBCONSUMERKEY: ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}
  DEVHUBJWTKEYFILE: devhub.key
  GITHUB_PAT: ${{ secrets.QBRIX_GITHUB_PAT}}
  USE_TEMPLATE: true
  TEMPLATEID: LATEST
  TEMPLATE_INSTANCE: NA135
  SFDX_DISABLE_DNS_CHECK: true
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  BUILD_SUFFIX: SDO

jobs:
  qlabs_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Core Setup - key for jwt auth
        run: echo "${{ secrets.QBRIX_DEVHUB_PRIVATE_KEY }}" > devhub.key

      # Install SFDX
      - name: Install SFDX
        run: npm install @salesforce/cli --global

      # We will use a common app with a common key -
      - name: Create SFDX Session for QLABS Service Account
        run: sf org login jwt -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} -d -f devhub.key -i ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}

      - name: Extract the accesstoken
        run: sf org display -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} --json > qlab_tmp.json

      - name: extract the accesstoken for qlabs
        uses: sergeysova/jq-action@v2
        id: qlabs_accesstoken
        with:
          cmd: jq '.result.accessToken' qlab_tmp.json -r

      - name: Install PYYaml
        run: python3 -m pip install pyyaml

      - name: Write python File
        uses: "DamianReeves/write-file-action@master"
        with:
          path: ${{ github.workspace }}/qlab_publish.py
          write-mode: overwrite
          contents: |
            import yaml
            import os
            import requests
            import json
            filepath='${{ github.workspace }}/cumulusci.yml'
            inputsfile = '${{ github.workspace }}/qbrix_local/inputs/required.json'
            if(os.path.isfile(filepath)):
                with open(filepath, 'r') as stream:
                  yamldata = yaml.safe_load(stream)
                  url = "https://qlabs-org.my.salesforce.com/services/apexrest/NGQBrixContentService"

                  payload = json.dumps(yamldata)
                  payloaddic = json.loads(payload)
                  print(type(payload))
                  payloaddic["github_repository_id"] = "${{ github.repository_id }}"
                  payloaddic["github_repository_url"] = "${{ github.repositoryUrl }}"
                  payloaddic["github_sha"] = "${{ github.sha }}"
                  payload=json.dumps(payloaddic)

                  #check for a required parameters object
                  if (os.path.isfile(inputsfile)):
                    inputcontent = open(inputsfile, "r")
                    inputjson = inputcontent.read()
                    inputsdict = json.loads(inputjson)

                    if("parameters" in inputsdict):
                      print('Parameters found')
                      print(payload)
                      tempPayload=json.loads(payload)
                      tempPayload["parameters"]=inputsdict["parameters"]
                      payload=json.dumps(tempPayload)

                  headers = {
                      'Authorization': 'Bearer ${{ steps.qlabs_accesstoken.outputs.value }}',
                      'Content-Type': 'application/json'
                  }
                  requests.request("POST", url, headers=headers, data=payload)

      - name: Run the publish
        run: python3 ${{ github.workspace }}/qlab_publish.py
